config/routes.rb
MegaOglasnik::Application.routes.draw do
  root :to => 'application#home'
  get "sessions/new"
  resources :users
  resources :sessions
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/activate' => 'users#activate'
  get '/logout' => 'sessions#destroy'

  get 'home' => 'application#home', as: 'application'
  get 'login' => 'sessions#new'

  get '/home/language/bosnian' => 'users#change_to_bosnian'
  get '/home/language/english' => 'users#change_to_english'
  get '/home/language/default' => 'users#change_to_default'

resources :dashboard
match '/dashboards' => 'dashboard#new'
resources :categories
resources :ads

get '/search' => 'ads#search'  
post '/search' => 'ads#search'

match '/test' => 'application#test'

get '/sponsored_ads' => 'ads#get_sponsored_ads'
get '/new_ads' => 'ads#get_latest_ads'
get '/add_to_cart' => 'ads#add_to_cart'
get 'ads/:id/comments/new' => 'comments#new', as: 'comments'
post 'ads/comments' => 'comments#create', as: 'comments'
get 'ads/:id/comments' => 'comments#index', as: 'comments'

resources :partial_views, only: [:show]
get 'partial_view/index' => 'partial_views#index'
get 'categories/:id' => 'categories#show'
get 'myads' => 'users#myAds'
get 'users/:id/ads' => 'users#getusersads'
post 'users/:id/upload_photo' => 'users#upload_photo'
get 'ads/delete/:id' => 'ads#destroy'
post 'ads/:id/upload_photo' => 'ads#upload_photo'

post 'reservations' => 'reservations#create'
get 'reservations/:id' => 'ads#show'

get 'recieved_messages' => 'messages#recieved'
get 'sent_messages' => 'messages#sent'  
post 'create_message' => 'messages#write_message'
get 'show_messages' => 'messages#index' 
get 'session' => 'sessions#show'
get 'ae' => 'ads#ae'
get 'ee' => 'ads#ee'
get 'ri' => 'ads#ri'
get 'tk' => 'ads#tk'
get 'ae/:id' => 'ads#aegodine'
get 'ee/:id' => 'ads#eegodine'
get 'ri/:id' => 'ads#rigodine'
get 'tk/:id' => 'ads#tkgodine'
get 'toprated' => 'ads#get_top_rated'
get 'reservated' => 'ads#reservated'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  attr_accessible :academic_year, :category_id, :description, :expirytime,:picture_path, :price, :rating,:section, :sold,:sponsored, :timestamp, :title, :user_id, :author, :forexchange
belongs_to :user
belongs_to :category
has_one :item
has_many :pictures
has_many :comments

validates :title, :presence => true
validates :price, :presence => true
validates :section, :presence => true
validates :academic_year, :presence => true
validates :price, :numericality => { :greater_than_or_equal_to => 0 }
validates :academic_year, :numericality => true
def self.search(search)
  search_condition = "%" + search + "%"
  find(:all, :conditions => ['title LIKE ? OR description LIKE ?', search_condition, search_condition])
end


end

app/controllers/ad_controller.rb
class AdController < ApplicationController
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

  before_filter :authenticate_user!, :only => [:new,:edit,:destroy]
  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ads }
    end
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
    @ad = Ad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ad }
    end
  end

  # GET /ads/new
  # GET /ads/new.json
  def new
    @categories=Category.all
    @ad = Ad.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ad }
    end
  end

  # GET /ads/1/edit
  def edit
    @ad = Ad.find(params[:id])
  end
    
 def upload_picture
  uploaded_io = params[:file]
  @ad=Ad.find(params[:id]) 
  @naziv_slike =params[:id].to_s
  @ad.picture_path = "/images/products/product" + @naziv_slike + ".jpg"
  @ad.save
    @filename = "product" + @naziv_slike
  File.delete("#{Rails.root}/public/images/products/#{@filename}") if File.exist?("#{Rails.root}/public/images/products/#{@filename}")
  File.open(Rails.root.join('public', 'images/products', "product" + @naziv_slike + ".jpg"), 'wb') do |file|
  file.write(uploaded_io.read)
  end
  
  render json: @naziv_slike
 end

  # POST /ads
  # POST /ads.json
  def create
  
    
    @ad = Ad.new(params[:ad])
#    @ad.user_id = session[:user_id]
    @ad.sold = false
    @ad.rating = 0
    @ad.ratingsum = 0
    @ad.ratingsnumber = 0
    @ad.section=params[:section]
    @ad.academic_year=params[:academic_year]
    @ad.picture_path = "/images/products/product.jpg"
    respond_to do |format|
      if @ad.save
        @item=Item.new
        @item.category_id=params[:category_id]
        @item.ad_id=@ad.id
        @item.name=@ad.title
        @item.price=@ad.price
        @item.save
        format.html { redirect_to @ad, notice:  (t :ad_successfully_added) }
        format.json { render json: @ad, status: :created, location: @ad }
      else
        format.html { render action: "new" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ads/1
  # PUT /ads/1.json
  def update
    @ad = Ad.find(params[:id])
    @item=Item.where(ad_id: @ad.id)
    respond_to do |format|
      if @ad.update_attributes(params[:ad])
        format.html { redirect_to @ad, notice: (t :ad_successfully_updated) }
        format.json { render json: @ad }
              @ad.rating=params[:rating]
              @ad.ratingsnumber+=1
              @ad.ratingsum+=@ad.rating
              @ad.rating= @ad.ratingsum / @ad.ratingsnumber
              @ad.save  
      else
        format.html { render action: "edit" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end
    
def upload_photo
  uploaded_io = params[:file]
  @ad=Ad.find(params[:id]) 
  @naziv_slike =params[:id]
  @ad.picture_path = "/images/products/product" + @naziv_slike + ".jpg"
  @ad.save
  @filename = "product" + @naziv_slike
  File.delete("#{Rails.root}/public/images/users/#{@filename}") if File.exist?("#{Rails.root}/public/images/users/#{@filename}")
  File.open(Rails.root.join('public', 'images/products', "product" + @naziv_slike + ".jpg"), 'wb') do |file|
  file.write(uploaded_io.read)
  end
  
  render json: @ad
 end
  
  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy
render json: 1
  end

  def search
  
  @search = Ad.search(params[:search])
  render json: @search

  
  end

  def get_sponsored_ads
    @sponsored_ads = Ad.where(sponsored: true)

    respond_to do |format|
      format.html { redirect_to ads_url }
      format.json { render json: @sponsored_ads }
    end
  end

  def get_latest_ads
    @last_ads = Ad.last(4)

    respond_to do |format|
      format.json { render json: @last_ads }
    end
    
  end

  def ae
  @ads = Ad.where(section: 'AE').all
render json: @ads
  end
    
   def ee
    @ads = Ad.where(section: 'EE').all
render json: @ads
  end

     def ri
    @ads = Ad.where(section: 'RI').all
render json: @ads
  end
    
     def tk
    @ads = Ad.where(section: 'TK').all
render json: @ads
  end
    
    def aegodine
     @ads = Ad.where("section = ? AND academic_year = ?", 'AE', params[:id]).all
    render json: @ads
    end
    
    def eegodine
     @ads = Ad.where("section = ? AND academic_year = ?", 'EE', params[:id]).all
    render json: @ads
    end
    
    def rigodine
     @ads = Ad.where("section = ? AND academic_year = ?", 'RI', params[:id]).all
    render json: @ads
    end
    
    def tkgodine
     @ads = Ad.where("section = ? AND academic_year = ?", 'TK', params[:id]).all
    render json: @ads
    end
    
    def get_top_rated
        @oglasi = Ad.where("rating >= ?", 9).all

        
        render json: @oglasi
    end
  def add_to_cart
    ad = Ad.find(params[:id])
    # @cart = Cart.new
    @cart = find_or_create_cart
    @cart.add_ad(ad)
    # session[:cart] = @cart
    redirect_to(:action => 'show_cart' )  
  end
 
    def reservated
    @id = session[:user_id]
    @ads = Reservation.where(user_id: @id).all
    render json: @ads
    end

  def show_cart
    # @cart = session[:cart]
    @cart = find_or_create_cart
  end

 private #--------------------

 def find_or_create_cart
  session[:cart] ||= Cart.new

 end

end

app/helpers/ad_helper.rb
module AdHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/views/ads/_form.html.erb
<link rel="stylesheet" href="stylesheets/ad.css">
 <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
        
        <!-- Optional theme -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
        <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

<br/>

<%= form_for(@ad) do |f| %>
  <% if @ad.errors.any? %>
    
      <ul>
      <% @ad.errors.full_messages.each do |msg| %>
        <li class="alert alert-danger"><%= msg %></li>
      <% end %>
      </ul>
  <% end %>

  <select name="category_id">
    <% Category.all.each do |category| %>
        <option value="<%= category.id %>"><%= category.name %></option>
    <% end %>
</select>

<%= f.file_field :picture %>
  
 <div class="input-group">
  <div class="field">
    <b><%= t :title , :class=> "input-group-label" %></b><br />
    <%= f.text_field :title, :class=> "form-control" %>
  </div> 
 
    <b ><%= t :price,:class=> "input-group-label" %></b><br />
    <div class="input-group">
    <%= f.text_field :price,:class=> "form-control" %>
    <span class="input-group-addon">KM</span>
    
  </div>


  <div class="field">
   <b><%= t :description,:class=>"input-group-label" %></b><br />
    <%= f.text_area :description,:class=> "form-control" %>
  </div>
 </div>
 <br>
 <button type="submit" class="btn btn-primary"> <%= t :next %></button>
 <%= link_to (t :back), ads_path, :class => "btn btn-default" %> 
<% end %>
</div>

app/views/ads/edit.html.erb
<div class="container">

<h1><%= t :editing_ad %></h1>

<%= render 'form' %>

</div>

app/views/ads/index.html.erb
<html>
<head>
<!-- bootstrap -->
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-2.0.3.min.js"></script> 
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>  

    <!-- x-editable (bootstrap version) -->
    <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.4.6/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet"/>
    <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.4.6/bootstrap-editable/js/bootstrap-editable.min.js"></script>
    
    <!-- main.js -->
    <script src="main.js"></script>
</head>
<body>
<div class="container">

<h2> <%= t :ads %></h2><br/>


<ul class="nav nav-tabs">
  <li><a href="/home"><%= t :home %></a></li>
  <li class="active"><a href="/ads"><%= t :ads %></a></li>
  <li><a href="/categories"><%= t :categories %></a></li>
  <li><a href="/users"><%= t :users %></a></li>
  <li><a href="/ads/new"><%= t :create_ad %></a></li>
  <li><a href="/dashboards"> Dashboard </a></li>
  
  
</ul>


</div>

<div class="container">

	<table class="table table-condensed">
  <tr class="row darkerBG">
    <th class="col-xs-1"><%= t :title %></th>
    <th class="col-xs-1"><%= t :price %></th>
    <th class="col-xs-1"><%= t :description %></th>
  </tr>
  </br>


  <tr class="row">
     <% @ads.each do |ad| %>  
    
    <td class="col-xs-1"><a href="#" id="title" data-title= "Enter title"><%= ad.title %></a></td>
    <td class="col-xs-1"><a href="#" id="price" data-url="ads/<%= ad.id %>"  data-title= "Enter price"><%= ad.price %></a></td>
    <td class="col-xs-1"><a href="#" id="description" data-url="ads/<%= ad.id %>"  data-title= "Enter description"><%= ad.description %></a></td> <br>

    <div class="btn-group" align="right">
    <td>
    <%= link_to (t :show), ad,:class => "btn btn-default" %>
    <%= link_to (t :edit), edit_ad_path(ad),:class => "btn btn-default" %>
    <%= link_to (t :destroy), ad, :method => :delete, data: { confirm: (t :you_sure) + "?" } %></td>
    </div>
   </tr>
   <br/>
<% end %>
</table>

<%= link_to (t :new_ad), new_ad_path,:class => "btn btn-default" %>
</div>



<br />




    <div id="wrap">
      <div class="container">
      </div>
    </div>
    <div id="footer">
<br/>
  <a href="http://localhost:3000/home">
    <font size="2"><div class="container" style="text-align: center" >Copyright © All Rights Reserved</div></font>
</a>
    </div>
</body>

</html>

app/views/ads/new.html.erb
<link rel="stylesheet" href="stylesheets/ad.css">
 <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
        
        <!-- Optional theme -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
        <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

<h1> Dodaj oglas</h1>
<div class="row" style="float: left; margin: 20px; width: 16%; ">


<br/>
<%= render 'form' %>
</div>
 
 

app/views/ads/search.html.erb
<h1><%= t :search_results %></h1>

<table>
  <tr>
    <th><%= t :title %></th>
    <th><%= t :price %></th>
    <th><%= t :description %></th>
  </tr>

<% @search.each do |ad| %>
  <tr>
    <td><%= ad.title %></td>
    <td><%= ad.price %></td>
    <td><%= ad.description %></td>
    
    <td><%= link_to (t :show), ad %></td>
    <td><%= link_to (t :edit), edit_ad_path(ad) %></td>
    <td><%= link_to (t :destroy), ad, method: :delete, data: { confirm: (t :you_sure) + "?" } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/ads/show.html.erb
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Easy Ajax</title>
    <script type="text/javascript" src="prototype.js"></script>
   


<link rel="stylesheet" href="stylesheets/ad.css">
 <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
        
        <!-- Optional theme -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
        <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</head> 
<body class="container">

<p>
<% unless notice.nil? %>
<div id="notice" class="alert alert-success sm-4"><%= notice %></div>
</br>
<% end %>
</p>

<p>
  <b><%= t :title %>:</b>
  <%= @ad.title %>
</p>

<p>
  <b><%= t :price %>:</b>
  <%= @ad.price%>
</p>

<p>
  <b><%= t :description %>:</b>
  <%= @ad.description%>
</p>
<%= link_to (t :edit), edit_ad_path(@ad),:class => "btn btn-default"%> 
<%= link_to (t :back), ads_path,:class => "btn btn-default" %>

</body>
</html>