config/routes.rb
MegaOglasnik::Application.routes.draw do
  root :to => 'application#home'
  get "sessions/new"
  resources :users
  resources :sessions
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/activate' => 'users#activate'
  get '/logout' => 'sessions#destroy'

  get 'home' => 'application#home', as: 'application'
  get 'login' => 'sessions#new'

  get '/home/language/bosnian' => 'users#change_to_bosnian'
  get '/home/language/english' => 'users#change_to_english'
  get '/home/language/default' => 'users#change_to_default'

resources :dashboard
match '/dashboards' => 'dashboard#new'
resources :categories
resources :ads

get '/search' => 'ads#search'  
post '/search' => 'ads#search'

match '/test' => 'application#test'

get '/sponsored_ads' => 'ads#get_sponsored_ads'
get '/new_ads' => 'ads#get_latest_ads'
get '/add_to_cart' => 'ads#add_to_cart'
get 'ads/:id/comments/new' => 'comments#new', as: 'comments'
post 'ads/comments' => 'comments#create', as: 'comments'
get 'ads/:id/comments' => 'comments#index', as: 'comments'

resources :partial_views, only: [:show]
get 'partial_view/index' => 'partial_views#index'
get 'categories/:id' => 'categories#show'
get 'myads' => 'users#myAds'
get 'users/:id/ads' => 'users#getusersads'
post 'users/:id/upload_photo' => 'users#upload_photo'
get 'ads/delete/:id' => 'ads#destroy'
post 'ads/:id/upload_photo' => 'ads#upload_photo'

post 'reservations' => 'reservations#create'
get 'reservations/:id' => 'ads#show'

get 'recieved_messages' => 'messages#recieved'
get 'sent_messages' => 'messages#sent'  
post 'create_message' => 'messages#write_message'
get 'show_messages' => 'messages#index' 
get 'session' => 'sessions#show'
get 'ae' => 'ads#ae'
get 'ee' => 'ads#ee'
get 'ri' => 'ads#ri'
get 'tk' => 'ads#tk'
get 'ae/:id' => 'ads#aegodine'
get 'ee/:id' => 'ads#eegodine'
get 'ri/:id' => 'ads#rigodine'
get 'tk/:id' => 'ads#tkgodine'
get 'toprated' => 'ads#get_top_rated'
get 'reservated' => 'ads#reservated'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :ad_id, :content, :timestamp, :user_id
  belongs_to :user
  belongs_to :ad
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_filter :authenticate_user!, :only => [:new,:edit,:destroy]
  
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.where(ad_id: params[:id]).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new
    @comment.save
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new
    @comment.user_id = session[:user_id]
    if @comment.user_id == nil 
        @comment.user_id = params[:user_id]
        end
    @comment.ad_id = params[:ad_id]
    @comment.content = params[:content]
    @user = User.find_by_id(@comment.user_id)
    @comment.user_username = @user.username
    @comment.timestamp = Time.now
    respond_to do |format|
      if @comment.save
        #format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment}
      else
        #format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<link rel="stylesheet" href="stylesheets/ad.css">
 <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
        
        <!-- Optional theme -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
        <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>


<%= form_for(@comment) do |f| %>

<div class="input-group">
  <div class="field">
   Komentar
    <%= f.text_field :content, :class=> "form-control" %>
  </div> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>User id</th>
    <th> Content</th>
    <th>Ad id</th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <th><%= comment.user_id %></th>
    <th> <%= comment.content %></th>
    <th><%= comment.ad_id %></th>
    </tr>
<% end %>
</table>

<br />

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |